### ISSUE TITLE
Audio Files are not being found

### ISSUE THREAD

**Issue by jhonatan-segura** [jdah/zigsteroids#1]
First I cloned this repo, then I cloned the raylib-zig repo by going to their git and copying the URL.
I went to the zigasteriords folder, I ran `zig build` I've built the file successfully, however when executing the lsr.exe file on zig-out folder, it outputs, the following message on the image.
![audio_device](https://github.com/jdah/zigsteroids/assets/97373782/88446cf4-af7b-4a05-996d-782aa0b6aee2)
![asteroids](https://github.com/jdah/zigsteroids/assets/97373782/e21cedb9-7922-4739-922e-42c1ba9170af)
Initially I built it with the audio files outside the SRC folder as the original repo, it prompted that error, then I moved the files to the SRC folder and it still outputs the same message.
No audio is being played.

**Comment by jdah** [comment]
you're running it from the zig-out folder, it expects the working directory to be project root.

**Comment by jugo-de-mora** [comment]
But that's where the executable is being created, do I have to move the executable or what do I have to do?
